### ISSUE TITLE
Commit checker always failes when pushing new branch

### ISSUE THREAD

**Issue by fredrikand** [tomasbjerre/simple-bitbucket-commit-checker#46]
EDIT: Using Stash fork, version 1.15

Enabled settings:

Exclude Merge Commits 
Exclude Tags Commits 
Require Author Email in Stash 
Require Author Name in Stash 
Check commit size (kb) : 15000

$ git push origin HEAD:auto_upgrade_scripts
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 614 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
remote: Simple Stash Commit Checker
remote: 
remote: Your commits did not pass the commit checker. Please amend your commits.
remote: refs/heads/auto_upgrade_scripts 0000000000 -> f4b9d20400
remote: 
remote: 
remote: f4b9d204001fceb29043171c10e7fee5102f4e16 My Name <my.name@company.com>
remote: >>> Use master-latest spec in auto-upgrade script
remote: 
remote: Using latest spec when running the AutoUpgrade scripts.
remote: 
remote: 
To https://stash.company.se/bitbucket/scm/xyz/test-repo.git
 ! [remote rejected] HEAD -> auto_upgrade_scripts (pre-receive hook declined)
error: failed to push some refs to 'https://stash.company.se/bitbucket/scm/xyz/test-repo.git'

**Comment by tomasbjerre** [comment]
This is the very first commits in a new repo right?

**Comment by fredrikand** [comment]
No, it is not the very first. We actually have 140´ commits before.

While the 0000000000 -> f4b9d20400 seems strange, I actually think I figured out why the checker failed my commit.
I had an empty rule group defined. When I removed it, the checker passed. 
Sorry for the confusion.

**Comment by tomasbjerre** [comment]
ok nice, so we can close it again?

**Comment by fredrikand** [comment]
Yes, can be closed.
