### ISSUE TITLE
Excluding a user

### ISSUE THREAD

**Issue by anessi** [tomasbjerre/simple-bitbucket-commit-checker#48]
The plugin works very nice, but now I'm stuck with the following situation: I need to exclude a user from the hook which is used from Jenkins to merge changes between branches after successful builds. This fails the 'Author name' check. From the settings I understand that there is a 'Service User' com.atlassian.bitbucket.user.UserType.SERVICE but how can I create this user or flag an existing user to become a service user?

Wouldn't it be much more flexible to allow a list of users being excluded from the checks? I guess my case would be covered by the service user, but sometimes you want some users to not have any restrictions (even temporarily to fix something). This is currently not possible. Do you see some other solution for the problem? Thanks!

**Comment by tomasbjerre** [comment]
This is released in 2.3 now, open issue again if not working!

**Comment by anessi** [comment]
Works nice now. Thanks for fixing!
