### ISSUE TITLE
Automatically enable sbcc for number of git repos in bitbucket

### ISSUE THREAD

**Issue by AkulBhatnagar** [tomasbjerre/simple-bitbucket-commit-checker#50]
Hi

Is there a way to enable sbcc configurations for number of git repos in bitbucket. 
I do not want to do that one-by-one. Please suggest a way to perform this in one go.

Please help.

**Comment by tomasbjerre** [comment]
I never did that. I know some people make scripts that uses bitbuckets rest api to apply settings to all repos. Perhaps such scripts can be found on google.

**Comment by AkulBhatnagar** [comment]
I tried to find those scripts as well, but no luck. I will still try and please let me know if you come across any.

**Comment by tomasbjerre** [comment]
I just submitted this plugin for approval in Atlassian Marketplace:
https://github.com/tomasbjerre/settings-synchronizer-for-bitbucket-plugin

It is a very quick job so dont expect it to work perfectly!

I think this is related to, so I'm closing this one. #25

**Comment by AkulBhatnagar** [comment]
Thanks for writing back.

This plugin can certainly help me, but it's not available at Atlassian Marketplace. Is there some other way to get his plugin installed.

**Comment by tomasbjerre** [comment]
It will be available soon. Within a few days.
You can download it from the release tab on github and upload it in
bitbucket server admin page.
Den 20 apr 2016 06:55 skrev "AkulBhatnagar" <notifications@github.com>:

**Comment by AkulBhatnagar** [comment]
That good news.

Looking at the add-on, I am curious to know if this can be used to synchronize​ all the add-ons settings

**Comment by tomasbjerre** [comment]
Not right now. But i will implement that also soon.
Den 20 apr 2016 07:07 skrev "AkulBhatnagar" <notifications@github.com>:

**Comment by AkulBhatnagar** [comment]
I have installed it in my bitbucket 4.3.2. But I am not able to handle it. I am wondering how will it work.

I have:
Project A
Repo-a
Repo-b

I have then manually enabled sbcc for repo-a
And when I tried to sync the settings for repo-b, I did nothing.

Anything wrong I did or if you can suggest a way to use it.

**Comment by tomasbjerre** [comment]
In your case you should go to the settings of repo-b and specify "from repo" as repo-a. Then press sync button.

**Comment by AkulBhatnagar** [comment]
That's exactly what I did.

I went to repo-b settings 
Pressed synchronization
Select Repo-a in "from repo"
Check "Repository Hooks"
Press "sync now"

When I pressed "sync now" button, it actually did nothing (not even reloaded my window)

**Comment by tomasbjerre** [comment]
Did you press save first?

**Comment by AkulBhatnagar** [comment]
Yes I did that as well

**Comment by AkulBhatnagar** [comment]
Is it compatible with v 4.3.2

**Comment by tomasbjerre** [comment]
Yes its compatible.

If you hit F12 and look at the network and maby console tab. Any hints there? You should see some calls when pressing save and sync.

**Comment by AkulBhatnagar** [comment]
I checked the traces at F12 console tab, When I press save nothing happened.

But when I pressed sync now button, see what it gave me:

POST http://<hostanme>:7990/rest/ssfb/1.0/globalsync 500 (Internal Server Error)
k.cors.a.crossDomain.send	@	batch.js?locale=en-US:29
n.extend.ajax	@	batch.js?locale=en-US:29
c	@	se.bjurr.ssfb.settings-synchronizer-for-bitbucket:repoadmin.js:88
(anonymous function)	@	se.bjurr.ssfb.settings-synchronizer-for-bitbucket:repoadmin.js:134
n.event.dispatch	@	batch.js?locale=en-US:28
r.handle	@	batch.js?locale=en-US:28

**Comment by AkulBhatnagar** [comment]
Any help from traces

**Comment by tomasbjerre** [comment]
ok . You should have something in the logs of Bitbucket then.

I will do some more testing myself later today.

**Comment by AkulBhatnagar** [comment]
Thanks for your time, please keep me posted.

**Comment by tomasbjerre** [comment]
You may try 1.1:
https://github.com/tomasbjerre/settings-synchronizer-for-bitbucket-plugin/releases/tag/settings-synchronizer-for-bitbucket-1.1

**Comment by AkulBhatnagar** [comment]
Thanks for this early release and the good news is - it works.

Observation: I observed that settings have been replicated for first 25 repos only and not for remaining 6 repos (I have total 31 repos).

It seems to me as if there is some kind of default limit applied which is 25 for any rest-api. Am I correct

**Comment by tomasbjerre** [comment]
Should be fixed now, in 1.3

**Comment by AkulBhatnagar** [comment]
Yes, it has surely made some progress. But still few repos has been left. This time there is no specific pattern which I could observer. Majorly repos are covered but some of them got skipped.

**Comment by tomasbjerre** [comment]
How many repos do you have?
Den 22 apr 2016 07:12 skrev "AkulBhatnagar" <notifications@github.com>:

**Comment by AkulBhatnagar** [comment]
Its around 400+

**Comment by AkulBhatnagar** [comment]
Version 1.4 is a bang-on.
