### ISSUE TITLE
Performance degradation with larger user base(?)

### ISSUE THREAD

**Issue by fredrikand** [tomasbjerre/simple-bitbucket-commit-checker#54]
We just merged two AD used for Authentication and this added 7 times more users (~3000) and about 10 times more groups (~2000) in our directory. After this, the add-on is not possible to use. The performance is just to bad.
I have tested to connect Bitbucket to AD directly, or via JIRA and the builtin Crowd server. Same results.

**Empirical tests show that** 
* push 20 commits with the add-on enabled takes about 3 minutes.
* push 20 commits with the add-on disabled takes about 6 seconds.

**We have this config:**
(x) Exclude Tags Commits
(x) Require Author Email in Bitbucket
(x) Require Author Name in Bitbucket
Check commit size (kb) -> 15000

Enabling/Disabling config in sbcc does not seem to make that much a difference. Still the same results.
With ALL checks off, the push performance is back to normal.
Enable ONLY "Check commit size (kb)", which should not be related to users, also adds several minutes to the push action.

Our repo with problems has the following data
150` commits, 1.3GB, 10500 files

Another hosted repo, were all is working well, is much smaller. Same config as above.

**Comment by tomasbjerre** [comment]
Duplicate, https://github.com/tomasbjerre/simple-bitbucket-commit-checker/issues/53
