### ISSUE TITLE
size-checker is checking files not part of the pushed change-set

### ISSUE THREAD

**Issue by fredrikand** [tomasbjerre/simple-bitbucket-commit-checker#55]
Is it intentional that the size-checker is checking files that are added in previous commits?

Use case where this would be a problem:
* Checker limit set to 10000 (kb).
* Large file (14987kb) added back in 2012
* New change-sets do not touch the large file, but is still rejected due to the large fil added back in 2012

**Comment by tomasbjerre** [comment]
Try 2.7. I changed it so that it only checks files that were changed.

**Comment by fredrikand** [comment]
2.7 works the way I would expect.

Thank you!
