### ISSUE TITLE
Commit messages not validated when merging from a non-validated branch into a validated one

### ISSUE THREAD

**Issue by gcerverah** [tomasbjerre/simple-bitbucket-commit-checker#56]
I have successfully configured rules for my main branch and unchecked the "Exclude Merge Commits" option in order to enforce validation of any commits that are merged in.  However, everything goes through when merging and pushing:

% git merge branch-with-many-validation-rules-violations
% git push
remote: Simple Bitbucket Commit Checker
remote: 
remote: Accepted!
remote: 

Can you please tell me if this is expected or am I missing something in my setup?

**Comment by tomasbjerre** [comment]
It will check all new commits that are pushed. If you push commits to `branch-with-many-validation-rules-violations` then that will be the time when they are checked.

Perhaps you pushed commits to that branch and later, with the hook enabled, pushed the merge? So the only new commit in the merge-push was the actual merge-commit?
