### ISSUE TITLE
Error when pushing deleted files

### ISSUE THREAD

**Issue by petervk2** [tomasbjerre/simple-bitbucket-commit-checker#59]
Hi, we've just started using this plugin, really happy with it so far, thanks!

I'm getting the following error when trying to push a commit where a file was deleted:
`remote: Simple Bitbucket Commit Checker`
`remote: `
`remote: Error while validating reference changes. Will allow all of them. "Missing unknown 0000000000000000000000000000000000000000"`

Have I missed something or...?

**Comment by tomasbjerre** [comment]
You should also have a stacktrace in your log. Can you find it?

**Comment by petervk2** [comment]
Sure, attached.

[catalina.2016-10-11.txt](https://github.com/tomasbjerre/simple-bitbucket-commit-checker/files/523585/catalina.2016-10-11.txt)

**Comment by tomasbjerre** [comment]
Should be fixed in 2.8 now! Open issue again if not working.

**Comment by petervk2** [comment]
Looks good, many thanks!
