### ISSUE TITLE
Using message variables in Regex

### ISSUE THREAD

**Issue by jvmbatista** [tomasbjerre/simple-bitbucket-commit-checker#61]
Hello,

Is it possible to add support, or use, the ${BITBUCKET_USER} variable in a regular expression?

I was trying the following in the branch checker ("/heads/dev/$\{BITBUCKET_USER\}/.+") but the variable is not replaced.

Best Regards
João

**Comment by tomasbjerre** [comment]
`${BITBUCKET_USER}` is the display name. You probably want the login name? I'm adding that as `${BITBUCKET_USER_SLUG}`.

I'll release this soon...

**Comment by jvmbatista** [comment]
Hello, 

Yes that's it. Branches have the developer username in the name so yes, that's what I was looking for.

Thanks for adding this ;)

**Comment by tomasbjerre** [comment]
This is released now. Open issue again if not working!

**Comment by jvmbatista** [comment]
Hi, just to let you know that it's working.
Thanks
