### ISSUE TITLE
Hide SBCC plugin disable option

### ISSUE THREAD

**Issue by glndgrgd** [tomasbjerre/simple-bitbucket-commit-checker#63]
We hacked the soy template to hide the "Disabled" button. However, we found out another disable button inside the popover. Can you help us out on how to hide the button too? Thanks!

**Comment by tomasbjerre** [comment]
Im not exactly sure witch button you mean.
Also what is the use case here? Why do you need to disable it?

**Comment by glndgrgd** [comment]
When SBCC plugin is configured, there will be a pop-up for the details of the plugin. On the lower right of the pop-up, there is a disable button between "save" and "cancel" buttons. We want the users of this plugin on our bitbucket to stop disabling this plugin since it will enable them to bypass the regex for the commit messages.

**Comment by tomasbjerre** [comment]
That is not part of the plugin.

And those users will still be able to disable the plugin with a rest call even if you remove the button.

Perhaps you want these users to not be admins.
