### ISSUE TITLE
Newline character in output

### ISSUE THREAD

**Issue by lexxssol** [tomasbjerre/simple-bitbucket-commit-checker#67]
simple-bitbucket-commit-checker/src/main/java/se/bjurr/sbcc/SbccPrinter.java:22

contains the following line: 

> public static String NL = System.getProperty("line.separator");

which gives CR+LF line separator on windows systems. 

However, this carriage return symbol introduces problems like this one: 

https://gitlab.com/tortoisegit/tortoisegit/issues/2921

I believe the proper way is to use system-independent line delimiter (always LF) or make this configurable.

What are your thoughts?

Thank you.

Best regards,
Alex.

**Comment by tomasbjerre** [comment]
I released this in 2.11. Open issue again if any problems!

**Comment by lexxssol** [comment]
Thanks for your help!
