### ISSUE TITLE
Require Matching Author Name validates against only Stash "username(userid)" field

### ISSUE THREAD

**Issue by araviteja** [tomasbjerre/simple-bitbucket-commit-checker#68]
Hi 
I am trying to configure plugin in our stash repository. We are implementing common user mapping across our CI tools(Jenkins,BBDC, etc).Currently SBCC plugin doesn’t have validation option with stash userid (User slug (username) of user in Bitbucket) .Currently it will validate User's Name and Email. The root of the issue is more related to Jenkins I think but I don't see them changing it. Jenkins builds its user database on the fly so when Jenkins comes across a git commit, it tries to look up the Jenkins user associated with the commit by either the user.name and user.email. If the user has never logged into Jenkins and thus does not yet have a user record populated with their user id, display name and email, Jenkins creates a new user record using the user.name as the user id. This then loses the correlation between the logged in user and their possible commits affecting various views. Once the wrong user

Although not git best practice, we are unable to use this plugin if we want to ensure consistency within Jenkins. Having an option in the SBCC UI to select validation on stash user id would help us deal with this. Can this use case be considered and added to plugin?

Reference Jenkins issue here: https://issues.jenkins-ci.org/browse/JENKINS-9016

**Comment by tomasbjerre** [comment]
Yes can definitely be added. But not for Stash, its very old now and I wont spend time on supporting it. Adding it for Bitbucket Server should be no problem.

**Comment by araviteja** [comment]
Thank you.  We will wait for your next release. BTW you have any date in your mind for us on when this can be added. ?

**Comment by tomasbjerre** [comment]
I think a couple of checkboxes can be added to solve this:
* Require that the commit authors name matches the Bitbucket users slug.
* Require that author name exists as user slug for at least one user in Bitbucket.

**Comment by tomasbjerre** [comment]
I released this now as 2.12. Hope that solves your problem. Open issue again if not working.

**Comment by araviteja** [comment]
Thanks a lot for your quick help. I have opened #69 where requesting to enable one option. Please take a look.
