### ISSUE TITLE
Requires to have option to validate commiter name with bitbucket user slug

### ISSUE THREAD

**Issue by araviteja** [tomasbjerre/simple-bitbucket-commit-checker#69]
Hi Tomas,

This is continuation of issue #68.

Some of our users will perform “git commit --amend”, “git rebase” where author and committer will be different and selecting this option “Require that the commit authors name matches the Bitbucket users slug” Will prevent this to happen as it will always look for condition where author and committer should match with bitbucket user slug. So in order to meet our requirement we need to validate the committer with bitbucket user slug. Something like below. Can this option be considered and added to plugin.?

“Require that committers name matches the Bitbucket user slug” 

Regards,
Raviteja

**Comment by tomasbjerre** [comment]
Yes, should be no problem.

But I think you could also instead use the option "Require Author Name As Userslug in Bitbucket". So that all commits are accepted as long as their author is matching a userslug. Not necessarily the userslug of the user pushing them, but any userslug for any user.

**Comment by araviteja** [comment]
When it comes to Jenkins. With the help of git change log plugin we can see the details of committer who commented the push. Whatever user mention in user.name in their git config will be showed here, not the Author name which is displayed at BBDC . So to have same user mapping we need to restrict both committer and author but we should not match both with the bitbucket user slug as they may differ in some scenarios (like git rebase etc..).

**Comment by tomasbjerre** [comment]
It is in 2.14 now. Open issue again if any problems.
