### ISSUE TITLE
In-browser editing bypasses hooks

### ISSUE THREAD

**Issue by generalpdiggs** [tomasbjerre/simple-bitbucket-commit-checker#70]
Bitbucket 4.14.5 (upgraded from 4.11.0) - now has in browser editing

Current sbcc plugin 2.14

---------------------------------------------------------------------------------

When editing in a browser and committing the change, nothing is checked by the plugin.  This messes with the policy we have in place of requiring proper author information, as well as verifying JIRA issues.   Though I am not sure if this is more an issue with Bitbucket, or with this plugin not detecting an event.

**Comment by tomasbjerre** [comment]
Note: Should probably go for the new SPI for this https://developer.atlassian.com/static/javadoc/bitbucket-server/latest/spi/reference/com/atlassian/bitbucket/hook/repository/PreRepositoryHook.html#preUpdate(com.atlassian.bitbucket.hook.repository.PreRepositoryHookContext, T)

**Comment by tomasbjerre** [comment]
https://community.atlassian.com/t5/Bitbucket-questions/Suggested-change-to-PreRepositoryHook/qaq-p/589213#M16567

**Comment by tomasbjerre** [comment]
https://developer.atlassian.com/bitbucket/server/docs/latest/tutorials-and-examples/controlling-when-pull-requests-can-be-merged.html

**Comment by tomasbjerre** [comment]
I released this as 3.0 and its only compatible with Bitbucket Server 5.0!

**Comment by generalpdiggs** [comment]
@tomasbjerre, we finally got around to testing upgrades with Bitbucket, along with the latest version of this plugin.  I am seeing "hook 'pre-receive-repository-hook' vetoed the file-edit request" in the logs now, but, the actual commit box just sits there and spins in the Bitbucket UI and there is not message to the user saying what the problem is.  I can open a new "issue" for this but thought I would check here first to see if that has come up at all?  Thanks!
