### ISSUE TITLE
Hook Validation is not working when creating a new branch. Allowing invalid users to create branch without validating the regexp and user details(email and slug)

### ISSUE THREAD

**Issue by araviteja** [tomasbjerre/simple-bitbucket-commit-checker#71]
Hi Tomas,

We observed that plugin is not validating the user email and user slug while creating a branch and it is  allowing  users to create the branch even though its regexp is not matching. Our bitbucket version is v5.1.0 and sbcc plugin version is 3.1.

When we try to push some changes to the already existing branch, Validation is working fine. When we creating new branch , That time only we are seeing this. Below is the log it will show and it will allow branch to create.

This validation is very important for us. it was working fine with previous bitbucket version(4.X). So can you please look in to this? 
Branch should not get created when it is not matching with regexp and branch should not get created  from invalid users whose email and slug is not in bitbucket. 

$ git push --set-upstream origin almadmin/AlM2
Total 0 (delta 0), reused 0 (delta 0)
remote: Simple Bitbucket Commit Checker
remote:
remote: Error while validating reference changes. Will allow all of them. "Commit '0000000000000000000000000000000000000000' does not exist in repository 'repo'."
remote:
remote: Create pull request for almAdmin/AlM2:
remote:   https://gitX.XXXXX.XXX/projects/XXXXX/repos/pXXX-XXXX/compare/commits?sourceBranch=refs/heads/almAdmin/AlM2
remote:
To https://gitX.XXXX.XXX/scm/XXXX/XXXXXXXX.git
 * [new branch]              almadmin/AlM2 -> almadmin/AlM2
Branch almadmin/AlM2 set up to track remote branch almadmin/AlM2 from origin

Thank you.

Regards,
Raviteja

**Comment by tomasbjerre** [comment]
Should be fixed now in 3.2. Open issue again if any problems!

**Comment by araviteja** [comment]
Thanks a lot Tomas for your quick help. Validation while creating new branch is working now. We faced new issue. Please refer issue#..https://github.com/tomasbjerre/simple-bitbucket-commit-checker/issues/73
