### ISSUE TITLE
NPE from se.bjurr.sbcc.UserValidator.shouldIgnoreServiceUser(UserValidator.java:29)

### ISSUE THREAD

**Issue by maciekm6k** [tomasbjerre/simple-bitbucket-commit-checker#75]
We see lot's of NullPointerExceptions in our Bitbucket log (sample below).  They appear to be written in batches, possibly as a result of Bitbucket background tasks. We would like to understand what is the possible reason and impact. It may be configuration issue on our side. It may be also relevant that we have 2 user directories - internal Bitbucket one and corporate Active Directory. 

I would appreciate your response,
-- Maciek

Sample log message:

> 2017-08-07 01:45:05,272 ERROR [AtlassianEvent::thread-10]  se.bjurr.sbcc.SbccRepositoryHook Error while validating reference changes. Will allow all of them. "null"
> java.lang.NullPointerException: null
>         at se.bjurr.sbcc.UserValidator.shouldIgnoreServiceUser(UserValidator.java:29)
>         at se.bjurr.sbcc.UserValidator.shouldIgnoreChecksForUser(UserValidator.java:20)
>         at se.bjurr.sbcc.SbccRepositoryHook.performChecks(SbccRepositoryHook.java:101)
>         at se.bjurr.sbcc.SbccPreReceiveRepositoryHook.preUpdate(SbccPreReceiveRepositoryHook.java:48)
>         at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.preUpdate(DefaultRepositoryHookService.java:583)
>         at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.preUpdate(DefaultRepositoryHookService.java:284)
>         at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.doCheck(DefaultMergeRequestCheckService.java:61)
>         at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.checkMergeability(DefaultMergeRequestCheckService.java:45)
>         at com.atlassian.stash.internal.pull.DefaultPullRequestService.canMerge(DefaultPullRequestService.java:246)
>         at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26)
>         at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
>         at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
>         at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
>         at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
>         at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
>         at nl.topicus.bitbucket.api.PullRequestListener.rescopedEvent(PullRequestListener.java:94)
>         at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:40)
>         at com.atlassian.stash.internal.event.AsyncBatchingInvokersTransformer$AsyncInvokerBatch.invoke(AsyncBatchingInvokersTransformer.java:109)
>         at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:38)
>         at com.atlassian.sal.core.executor.ThreadLocalDelegateRunnable.run(ThreadLocalDelegateRunnable.java:34)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.lang.Thread.run(Thread.java:748)
>         ... 100 frames trimmed
>

**Comment by cdancy** [comment]
Hey @tomasbjerre. @maciekm6k and I work together and we are seeing this issue after we recently upgraded from Stash (I believe 3.x) to latest Bitbucket and then enabled your plugin. Any help here would be greatly appreciated as our logs are filling up with these exceptions and making things unreadable.

**Comment by tomasbjerre** [comment]
One possible reason is [getCurrentUser](https://developer.atlassian.com/static/javadoc/bitbucket-server/4.0.0/api/reference/com/atlassian/bitbucket/auth/AuthenticationContext.html#getCurrentUser()) returning null. Do you have anonymous access?

**Comment by tomasbjerre** [comment]
Releasing 3.8 now with a possible fix!

**Comment by cdancy** [comment]
@tomasbjerre didn't even get time to respond and you've got a release going! Let us know when it's ready and we can give things a go.

**Comment by tomasbjerre** [comment]
it is available in the marketplace now =)

**Comment by tomasbjerre** [comment]
Can I close the issue?

**Comment by cdancy** [comment]
@tomasbjerre if we can keep it open for a few more days that would be great. Haven't followed back up with the team that implemented the new version yet to see if it resolved their issues. Will attempt to reach out today.

**Comment by cdancy** [comment]
@tomasbjerre working as expected. Thanks for fix and new release!!!

**Comment by tomasbjerre** [comment]
Nice!
