### ISSUE TITLE
Unable to push notes when sbcc plugin is enabled

### ISSUE THREAD

**Issue by mondayges** [tomasbjerre/simple-bitbucket-commit-checker#76]
Whenever we try to push a note to a commit, the sbcc plugin somehow treats it as a commit message where it will decline the push. Even if the note does match/conforms to the provided regex pattern in the plugin, it would still reject the push. Below are the steps done when the error was encountered:

## Added note namespace on the default commit
git notes --ref=release_notes add -m '[1708] Updated voltage dependency to 5.0.0'

## push the changes
git push origin refs/notes/release_notes

## Error message
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 310 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Simple Bitbucket Commit Checker
remote:
remote: refs/notes/release_notes 0000000000 -> 480a6d2a06
remote:
remote:
remote: 480a6d2a06bda6e2a860385509850070e90c3cc1 Gesmundo, Monday Morgen (mg578d) <mg578d@att.com>
remote: >>> Notes added by 'git notes add'
remote:
remote: - Invalid commit message. See https://wiki.web.att.com/display/GSCMTeam/GIT+Audit+of+Commit+Comments
remote:   Regex does not match: \[.{1,}\](?=[\s\S]+[a-zA-Z])(?![\s\S]*([A-Za-z])\1{5})([\s\S]*).{30,}
remote:
To ssh://codecloud.web.att.com:7999/st_monday/testing_repo.git
 ! [remote rejected] refs/notes/release_notes -> refs/notes/release_notes (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@codecloud.web.att.com:7999/st_monday/testing_repo.git'

**Comment by tomasbjerre** [comment]
Fixed in 3.9. Open issue again if any problems.
