### ISSUE TITLE
Unable to push tags when sbcc is enabled

### ISSUE THREAD

**Issue by eugenbuga** [tomasbjerre/simple-bitbucket-commit-checker#77]
Tags are treated as branches, if the name matches the regex it let's you push the tag, otherwise id does not.

remote: refs/tags/010, ^refs/heads/(?:feature|bugfix|hotfix|release)(?:\/).+
..
! [remote rejected] 010 -> 010 (pre-receive hook declined)
error: failed to push some refs to ..

**Comment by tomasbjerre** [comment]
Fixed in 3.9. Open issue again if any problems.

**Comment by eugenbuga** [comment]
thanks, works fine!

**Comment by tihobrazov** [comment]
I added a comment to RefChangeValidator.java that it should also check tag setting
