### ISSUE TITLE
SBCC not parsing commit messages

### ISSUE THREAD

**Issue by pemercer** [tomasbjerre/simple-bitbucket-commit-checker#78]
We wanted to use the SBCC to look for keywords in the commit message and block. Does not seem to matter what we check off for rules, it still will allow anything to be merged.

Bitbucket DC 5.3.2
SBCC version 3.9

**Comment by tomasbjerre** [comment]
Give an example that does not work.

**Comment by pemercer** [comment]
![screen shot 2017-10-30 at 10 36 09 am](https://user-images.githubusercontent.com/30251703/32176556-6ab267ee-bd5e-11e7-9d8a-dbeb0828aa4d.png)
![screen shot 2017-10-30 at 10 37 00 am](https://user-images.githubusercontent.com/30251703/32176562-6c336848-bd5e-11e7-8a33-b38f1e4ba533.png)
![screen shot 2017-10-30 at 10 37 11 am](https://user-images.githubusercontent.com/30251703/32176569-6eb3f380-bd5e-11e7-8b49-67ea3cae5a6b.png)

3 screen shots attached, commit message in my PR is test, nowhere close to meeting requirements. Even if I check box that it must match BOTH rules it still goes thru fine.

**Comment by tomasbjerre** [comment]
You are specifying the branch wrong. Here is what you have:
https://jex.im/regulex/#!flags=&re=release%2F*

You probably want the `.` before the `*` and also start with `refs/heads/`:
https://jex.im/regulex/#!flags=&re=refs%2Fheads%2Frelease%2F.*

**Comment by pemercer** [comment]
Thanks will test out the branch syntax

**Comment by pemercer** [comment]
Figured it out, since this is a pre-commit hook it should be enabled for all branches

**Comment by tomasbjerre** [comment]
Is it solved? Can it be closed?

**Comment by pemercer** [comment]
So it does block commits based on commit message, what I am curious about is it has a section dealing with pull-requests and parsing the commit message there. We are looking to block commits on certain branches if the commit message in the pull request does not contain a specific text. Will the plugin enable that?

Thanks,
Pete Mercer

**Comment by tomasbjerre** [comment]
Yes that should work.
