### ISSUE TITLE
Works for tags?

### ISSUE THREAD

**Issue by khalprin** [tomasbjerre/simple-bitbucket-commit-checker#81]
I'm trying create a rule that prevents creating tags with an empty message. Should this work for that purpose?

I've got a group with one rule that says commits are 'Accepted' if 'All rules match'. My regex for the commit message is:
^(?!\#)(\s?)*\S+[\s\S\r\n]*
...to prevent empty messages or messages that start with "#".

I haven't checked any other options or provided any other regex strings. I can create tags with no/empty message, and tags with messages that start with the "#" character.

**Comment by tomasbjerre** [comment]
As long as you did not check the "exclude tag commits" then I think it should work. Looks like a correct regexp.

**Comment by khalprin** [comment]
I didn't check the 'exclude tag commits' but all of my tests failed. I
added tags with no message and with messages that start with "#". All were
accepted. I'm tagging through the Bitbucket interface shown when I view a
commit. What do you think...a bug?

**Comment by tomasbjerre** [comment]
I released 3.11 now that should fix this.

Only annotated tags are checked. I don't know how to find soft tags with Atlassians Git API https://docs.atlassian.com/bitbucket-server/javadoc/5.7.0/git-api/reference/com/atlassian/bitbucket/scm/git/command/package-summary.html

Open issue again if not working.

**Comment by khalprin** [comment]
The 3.11 version failed to install. I've attached a screenshot of the error shown.

![sbcc_error](https://user-images.githubusercontent.com/35819923/35518232-970d4b96-04d6-11e8-9d46-c421a814011d.png)

**Comment by tomasbjerre** [comment]
Which version did you upgrade from?

**Comment by khalprin** [comment]
I was using 2.14. It's installed in Bitbucket 4.11

**Comment by khalprin** [comment]
FYI, adding the plug-in from the atlassian marketplace still finds your previous version (2.14). I downloaded the update from this site and then used the 'upload' option in bitbucket to install the update.

**Comment by tomasbjerre** [comment]
Ok. That is how it is suppose to work. 2.14 is the latest one compatible with your installation.

https://marketplace.atlassian.com/plugins/se.bjurr.sscc.sscc/versions

**Comment by khalprin** [comment]
Ah...I didn't see that. Thank you. We've actually got an update scheduled for the end of the day today. I'll try it again tomorrow.

Thanks again.

**Comment by khalprin** [comment]
After our bitbucket upgrade to 5.7, this still doesn't appear to work. I can add a tag with no description and one that starts with "#". I've got the hook installed (it shows version 3.11). It's enabled in the bitbucket administration settings, in the project and in the repository I'm test with. Is there any other information I can provide?

**Comment by tomasbjerre** [comment]
This works for me:
```
bjerre@bjerre-ubuntu:~/sandbox/rep_1$ git push --tags
Password for 'http://admin@localhost:7990': 
Räknar objekt: 1, klart.
Skriver objekt: 100% (1/1), 162 bytes | 162.00 KiB/s, klart.
Total 1 (delta 0), reused 0 (delta 0)
remote: At least one change is not ok
remote: refs/tags/tagname-1.0 0000000000 -> 2f0eb27390
remote: 
remote: 
remote: tag tagname-1.0 Tomas Bjerre <tomas.bjerre85@gmail.com>
remote: >>> 
remote: 
remote: - the group
remote:   the regexp: ^(?!#)(\s?)\S+[\s\S\r\n]
remote: 
remote: 
remote: Simple Bitbucket Commit Checker
remote: 
To http://localhost:7990/bitbucket/scm/project_1/rep_1.git
 ! [remote rejected] tagname-1.0 -> tagname-1.0 (pre-receive hook declined)
error: misslyckades sända vissa referenser till "http://admin@localhost:7990/bitbucket/scm/project_1/rep_1.git"
bjerre@bjerre-ubuntu:~/sandbox/rep_1$ git tag -d tagname-1.0 
Tog bort tagg "tagname-1.0" (var 2f0eb27)
bjerre@bjerre-ubuntu:~/sandbox/rep_1$ git tag -a tagname-1.0 -m "asd"
bjerre@bjerre-ubuntu:~/sandbox/rep_1$ git push --tags
Password for 'http://admin@localhost:7990': 
Räknar objekt: 1, klart.
Skriver objekt: 100% (1/1), 165 bytes | 165.00 KiB/s, klart.
Total 1 (delta 0), reused 0 (delta 0)
remote: Simple Bitbucket Commit Checker
remote: 
To http://localhost:7990/bitbucket/scm/project_1/rep_1.git
 * [new tag]         tagname-1.0 -> tagname-1.0
bjerre@bjerre-ubuntu:~/sandbox/rep_1$ 
```

![sc](https://user-images.githubusercontent.com/439571/35640079-6fb23e84-06bc-11e8-82bb-3b793d6fa6b7.png)

**Comment by khalprin** [comment]
I'm not an expert, but it looks like you're doing a push with a tag. I'm adding a tag with a commit directly in the bitbucket interface (shown below). Could that be the difference?
![add_tag](https://user-images.githubusercontent.com/35819923/35645676-37ba3e5c-0692-11e8-9002-6bbc728acbe3.png)
