### ISSUE TITLE
does it support the bitbucket cloud ? 

### ISSUE THREAD

**Issue by kiranpachava** [tomasbjerre/simple-bitbucket-commit-checker#82]
Hi,

Shall i use this add on to bitbucket cloud, if possible what is the procedure, when i try to include the install add-on from url option i was getting the error.

**The add-on server returned invalid data. Please contact the add-on vendor for help. Here's the error we encountered - The content-type header was application/java-archive;charset=UTF-8, but we expected application/json.**

How to integrate this to bitbucket cloud.

Regards,
Kiran

**Comment by tomasbjerre** [comment]
No not supported.

**Comment by kiranpachava** [comment]
Thanks, any plans to support it ?

**Comment by tomasbjerre** [comment]
No. It is a completely different product.

Den 13 feb. 2018 06:49 skrev "kiranpachava" <notifications@github.com>:

**Comment by kiranpachava** [comment]
sure, Thanks :)

**Comment by kiranpachava** [comment]
Do we have a tool just like this for bitbucket cloud ?

**Comment by tomasbjerre** [comment]
I dont know.

Den 13 feb. 2018 06:53 skrev "kiranpachava" <notifications@github.com>:
