### ISSUE TITLE
Bitbucket Server 6

### ISSUE THREAD

**Issue by tomascassidy** [tomasbjerre/simple-bitbucket-commit-checker#95]
Will this plugin be updated to support Bitbucket Server 6?  Is there anything that needs to be done/tested for code, or is it just marking the plugin as supported on the atlassian marketplace?

**Comment by tomasbjerre** [comment]
Made a quick test, seems to work. Only available from GitHub now: https://github.com/tomasbjerre/simple-bitbucket-commit-checker/releases

**Comment by tomascassidy** [comment]
Thanks.  The github release seems to install ok here.
